# Generated by Django 4.2.11 on 2026-05-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_department_leader_alter_member_department_userrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('worship', 'Worship Service'), ('prayer', 'Prayer Session'), ('special', 'Special Event'), ('youth', 'Youth Program'), ('outreach', 'Community Outreach'), ('meeting', 'Church Meeting'), ('seminar', 'Seminar / Workshop'), ('other', 'Other')], default='worship', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='members.member')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visitor', models.BooleanField(default=False)),
                ('visitor_name', models.CharField(blank=True, max_length=100)),
                ('visitor_phone', models.CharField(blank=True, max_length=20)),
                ('visitor_address', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='members.member')),
            ],
            options={
                'ordering': ['recorded_at'],
                'unique_together': {('event', 'member')},
            },
        ),
    ]
