# Generated by Django 4.2.11 on 2026-05-26 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitheOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Regular Offering'), ('thanksgiving', 'Thanksgiving'), ('building', 'Building Fund'), ('missions', 'Missions'), ('other', 'Other')], default='tithe', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('recorded_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='members.member')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('prepared_by', models.CharField(max_length=100)),
                ('prepared_date', models.DateField(auto_now_add=True)),
                ('total_members', models.PositiveIntegerField(default=0)),
                ('active_members', models.PositiveIntegerField(default=0)),
                ('new_baptisms', models.PositiveIntegerField(default=0)),
                ('transfers_in', models.PositiveIntegerField(default=0)),
                ('transfers_out', models.PositiveIntegerField(default=0)),
                ('deceased', models.PositiveIntegerField(default=0)),
                ('avg_sabbath_attendance', models.PositiveIntegerField(default=0)),
                ('avg_midweek_attendance', models.PositiveIntegerField(default=0)),
                ('total_tithe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_offering', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bible_study_participants', models.PositiveIntegerField(default=0)),
                ('outreach_contacts', models.PositiveIntegerField(default=0)),
                ('highlights', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('prayer_requests', models.TextField(blank=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BaptismRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('baptism', 'Baptism'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('reclaimed', 'Reclaimed'), ('deceased', 'Deceased'), ('missing', 'Missing')], max_length=20)),
                ('date', models.DateField()),
                ('officiating_pastor', models.CharField(blank=True, max_length=100)),
                ('transfer_church', models.CharField(blank=True, help_text='For transfers: source/destination church', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baptism_records', to='members.member')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BibleStudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('sabbath_school_attendance', models.PositiveSmallIntegerField(default=0)),
                ('personal_study_days', models.PositiveSmallIntegerField(default=0)),
                ('completed_lesson', models.BooleanField(default=False)),
                ('outreach_count', models.PositiveSmallIntegerField(default=0, help_text='Number of people shared Gospel with')),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_study', to='members.member')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('member', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service_type', models.CharField(choices=[('sabbath', 'Sabbath Service'), ('midweek', 'Midweek Prayer'), ('youth', 'Youth Service'), ('other', 'Other')], default='sabbath', max_length=20)),
                ('present', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='members.member')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('member', 'date', 'service_type')},
            },
        ),
    ]
