# Generated by Django 4.2.11 on 2026-05-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_department_leader_alter_member_department_userrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('health', 'Health & Healing'), ('family', 'Family & Relationships'), ('financial', 'Financial'), ('spiritual', 'Spiritual Growth'), ('counseling', 'Counseling Needed'), ('bereavement', 'Bereavement'), ('other', 'Other')], default='other', max_length=20)),
                ('request', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('being_prayed', 'Being Prayed For'), ('answered', 'Answered'), ('closed', 'Closed')], default='open', max_length=20)),
                ('pastor_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='members.member')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
