# Generated by Django 4.2.11 on 2026-05-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_department_leader_alter_member_department_userrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('pastor', 'Pastor'), ('elder', 'Church Elder'), ('secretary', 'Church Secretary'), ('treasurer', 'Treasurer'), ('leader', 'Department / Group Leader'), ('member', 'Regular Member')], default='member', max_length=20),
        ),
    ]
