# Generated by Django 4.2.11 on 2026-05-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred Out'), ('deceased', 'Deceased')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['membership_status', 'gender'], name='members_mem_members_69f7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name', 'first_name'], name='members_mem_last_na_92a910_idx'),
        ),
    ]
